# ===== SECRET FOR MYSQL DATABASE =====
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
type: Opaque
stringData:
  username: petclinic
  password: petclinic
---
# ===== SECRET FOR MYSQL EXPORTER =====
apiVersion: v1
kind: Secret
metadata:
  name: mysql-dsn
type: Opaque
stringData:
  DATA_SOURCE_NAME: "petclinic:petclinic@tcp(mysql.default.svc.cluster.local:3306)/petclinic"
---
# ===== PVC =====
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
# ===== MYSQL STATEFULSET =====
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql        
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              value: petclinic
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          args:
            - "--default-authentication-plugin=mysql_native_password"
  volumeClaimTemplates:         
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
---
# ===== MYSQL SERVICE =====
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
# ===== MYSQL EXPORTER =====
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql.default.svc.cluster.local 3306; do
                echo "Waiting for MySQL..."
                sleep 2
              done
          imagePullPolicy: IfNotPresent
      containers:
        - name: exporter
          image: prom/mysqld-exporter:v0.14.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-dsn
                  key: DATA_SOURCE_NAME
---
# ===== MYSQL EXPORTER SERVICE =====
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
