apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  strategy: {}
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/petclinic
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: demo-db
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: demo-db
        image: your image
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
        resources: {}
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z mysql 3306; do echo "waiting for mysql"; sleep 5; done;
        image: busybox:1.36
        name: wait-for-mysql
        resources: {}
status: {}
